In [84]:

2# data manipulation

import pandas as pd
import numpy as np
import re
import string
## methods and stopwords text processing
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
## machine learning libraries
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import warnings
warnings.filterwarnings("ignore")

In [86]:
df = pd.read_csv("Tweet_NFT.xlsx - Sheet1.csv")

In [87]:
df

,id,tweet_text,tweet_created_at,tweet_intent
0,1212762,@crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...,2022-08-06T16:56:36.000Z,Community
1,1212763,Need Sick Character artâ“#art #artist #Artist...,2022-08-06T16:56:36.000Z,Giveaway
2,1212765,@The_Hulk_NFT @INagotchiNFT @Tesla @killabears...,2022-08-06T16:56:35.000Z,Appreciation
3,1212766,@CryptoBatzNFT @DarekBTW The first project in ...,2022-08-06T16:56:35.000Z,Community
4,1212767,@sashadysonn The first project in crypto with ...,2022-08-06T16:56:34.000Z,Community
...,...,...,...,...
127448,1278721,"@Jason My company Universe is solving this, an...",2022-08-08T03:32:01.000Z,NaN
127449,1278723,@BosoTokyo Many will get rekt in this NFT,2022-08-08T03:32:00.000Z,NaN
127450,1278724,@leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...,2022-08-08T03:32:00.000Z,NaN
127451,1278725,@1kz3ro @UNLEASHED_NFT I love this job,2022-08-08T03:31:59.000Z,NaN
127452,1278729,@Shill_Ronin @UNLEASHED_NFT my proof https://t...,2022-08-08T03:31:58.000Z,NaN

In [112]:
corpus=[]

for i in range(0, 127453):
  review = re.sub('[^a-zA-Z]', ' ', df['tweet_text'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

In [114]:
df['Tweet_text'] = corpus

In [116]:
df = df.drop('tweet_text', axis=1)

In [122]:
import re
def tokenization(text):
    tokens = re.split('W+',text)
    return tokens
#applying function to the column
df['msg_tokenied']= df['Tweet_text'].apply(lambda x: tokenization(x))

In [123]:
df

,id,tweet_created_at,tweet_intent,Tweet_text,msg_tokenied
0,1212762,2022-08-06T16:56:36.000Z,Community,crypto brodi ecolog moonrunnersnft itsukinft t...,[crypto brodi ecolog moonrunnersnft itsukinft ...
1,1212763,2022-08-06T16:56:36.000Z,Giveaway,need sick charact art art artist artist anim i...,[need sick charact art art artist artist anim ...
2,1212765,2022-08-06T16:56:35.000Z,Appreciation,hulk nft inagotchinft tesla killabearsnft elon...,[hulk nft inagotchinft tesla killabearsnft elo...
3,1212766,2022-08-06T16:56:35.000Z,Community,cryptobatznft darekbtw first project crypto mo...,[cryptobatznft darekbtw first project crypto m...
4,1212767,2022-08-06T16:56:34.000Z,Community,sashadysonn first project crypto move earn ast...,[sashadysonn first project crypto move earn as...
...,...,...,...,...,...
127448,1278721,2022-08-08T03:32:01.000Z,NaN,jason compani univers solv got columbia startu...,[jason compani univers solv got columbia start...
127449,1278723,2022-08-08T03:32:00.000Z,NaN,bosotokyo mani get rekt nft,[bosotokyo mani get rekt nft]
127450,1278724,2022-08-08T03:32:00.000Z,NaN,leeneedham kibainuworld hodl offici koacombat ...,[leeneedham kibainuworld hodl offici koacombat...
127451,1278725,2022-08-08T03:31:59.000Z,NaN,kz ro unleash nft love job,[kz ro unleash nft love job]
127452,1278729,2022-08-08T03:31:58.000Z,NaN,shill ronin unleash nft proof http co di p gz,[shill ronin unleash nft proof http co di p gz]

In [134]:
#importing nlp library
import nltk
#Stop words present in the library
stopwords = nltk.corpus.stopwords.words('english')

#defining the function to remove stopwords from tokenized text
def remove_stopwords(text):
    output= [i for i in text if i not in stopwords]
    return output
#applying the function
df['no_stopwords']= df['msg_tokenied'].apply(lambda x:remove_stopwords(x))

In [150]:
#importing the Stemming function from nltk library
from nltk.stem.porter import PorterStemmer
#defining the object for stemming
porter_stemmer = PorterStemmer()
#defining a function for stemming
def stemming(text):
    stem_text = [porter_stemmer.stem(word) for word in text]
    return stem_text
df['msg_stemmed']=df['no_stopwords'].apply(lambda x: stemming(x))

In [153]:
from nltk.stem import WordNetLemmatizer
#defining the object for Lemmatization
wordnet_lemmatizer = WordNetLemmatizer()
#defining the function for lemmatization
def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text
df['msg_lemmatized']=df['no_stopwords'].apply(lambda x:lemmatizer(x))

In [156]:
def get_feature_vector(df):
    vector = TfidfVectorizer(sublinear_tf=True)
    vector.fit(df)
    return vector